services:
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/conf/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ./boughts:/var/www/
      - ./logs/nginx:/var/log/nginx 
    networks:
      - app-network
    restart: always
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - ./boughts:/var/www            
      - ./logs/php:/var/log/php-fpm 
      # - ./boughts/.env:/var/www/.env
    networks:
      - app-network
    command: ["php-fpm7.2", "-F"]

networks:
  app-network:
    driver: bridge